alter sequence usr_id_seq restart with 1;
alter sequence user_n_quiz_id_seq restart with 1;
alter sequence history_results_id_seq restart with 1;
alter sequence user_answer_id_seq restart with 1;
alter sequence quiz_id_seq restart with 1;
alter sequence quiz_n_quiz_id_seq restart with 1;
alter sequence key_quiz_id_seq restart with 1;
alter sequence question_id_seq restart with 1;
alter sequence answer_id_seq restart with 1;
